def lettres(x): #Fonction qui remplace les accents etc. en lettres normales et les met en majuscules
    x = x.replace("é","e")
    x = x.replace("è","e")
    x = x.replace("ë","e")
    x = x.replace("ê","e")
    x = x.replace("à","a")
    x = x.replace("ã","a")
    x = x.replace("â","a")
    x = x.replace("ä","a")
    x = x.replace("á","a")
    x = x.replace("ç","c")
    x = x.replace("ù","u")
    x = x.replace("ü","u")
    x = x.replace("û","u")
    x = x.replace("ú","u")
    x = x.replace("ÿ","y")
    x = x.upper()
    return(x)